[project]
name = "ai-guardrails"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "guardrails-ai>=0.8.1",
    "ipykernel>=7.2.0",
    "openai>=2.21.0",
    "torch>=2.10.0",
    "transformers>=5.1.0",
]

[tool.uv.workspace]
members = [
    "ai-guardrails",
]
